version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Setting up tags...
      - DATE_TAG=$(date +%Y-%m-%d)
      - IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$DATE_TAG -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$DATE_TAG $IMAGE_URI:$DATE_TAG
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $IMAGE_URI:$IMAGE_TAG

  # post_build:
  #   commands:
  #     - echo Build completed on `date`
  #     - echo Pushing the Docker image...
  #     - docker push $IMAGE_URI:$IMAGE_TAG
  #     - docker push $IMAGE_URI:$DATE_TAG
  #     - echo Build Successful
  #     - printf '[{"name":"churn-application-container","imageUri":"%s"}]' $IMAGE_URI:$IMAGE_TAG > imagedefinitions.json
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_URI:$IMAGE_TAG
      - docker push $IMAGE_URI:$DATE_TAG
      - echo Build Successful
      - printf '[{"name":"churn-application-container","imageUri":"%s"}]' $IMAGE_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json  # verify file was created

# artifacts:
#   files:
#     - imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
  base-directory: .
  discard-paths: yes
